CREATE TABLE Usuarios(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(50) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Senha VARCHAR(255) NOT NULL,
    CriadoEm TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    AtualizadoEm TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Deletado BOOLEAN DEFAULT 0
);

CREATE TABLE SaldoTotal (
    ID INT AUTO_INCREMENT,
    UsuarioID INT,
    Saldo DECIMAL(10, 2),
    PRIMARY KEY (ID),
    FOREIGN KEY (UsuarioID) REFERENCES Usuarios(ID)
);

CREATE TABLE Categorias(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(50) NOT NULL,
    Descricao VARCHAR(255),
    CriadoEm TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    AtualizadoEm TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Deletado BOOLEAN DEFAULT 0
);

CREATE TABLE Lancamentos(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    UsuarioID INT NOT NULL,
    CategoriaID INT NOT NULL,
    Descricao VARCHAR(255) NOT NULL,
    Valor DECIMAL(10, 2) NOT NULL,
    DataLancamento DATE NOT NULL,
    Tipo ENUM('receita', 'despesa') NOT NULL,
    CriadoEm TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    AtualizadoEm TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Deletado BOOLEAN DEFAULT 0,
    FOREIGN KEY (UsuarioID) REFERENCES Usuarios(ID),
    FOREIGN KEY (CategoriaID) REFERENCES Categorias(ID),
    INDEX (CategoriaID)
);

CREATE TABLE Metas(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    UsuarioID INT NOT NULL,
    Descricao VARCHAR(255) NOT NULL,
    Valor DECIMAL(10, 2) NOT NULL,
    DataInicio DATE NOT NULL,
    DataFim DATE NOT NULL,
    CriadoEm TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    AtualizadoEm TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Deletado BOOLEAN DEFAULT 0,
    FOREIGN KEY (UsuarioID) REFERENCES Usuarios(ID)
);

DELIMITER //
CREATE TRIGGER atualiza_saldo_apos_inserir_lancamento
AFTER INSERT ON Lancamentos
FOR EACH ROW
BEGIN
    UPDATE SaldoTotal 
    SET Saldo = Saldo + NEW.Valor
    WHERE UsuarioID = NEW.UsuarioID;
END;
//
DELIMITER ;